---
title: "ValenceComparison"
author: "Ryan Douglas"
date: "3/28/2019"
output: html_document
---

### Analyzes "Like" ratings for HRV data set

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(readxl)
library(lme4)
```

```{r}
hrv <- read.csv("/Users/DyanRouglas/Documents/Yale_data/HRV/HRVCleaned.csv", stringsAsFactors = FALSE)
ratings <- read.csv("/Users/DyanRouglas/Documents/Yale_data/HRV/ScanRatings_HRV.csv", stringsAsFactors = FALSE)
prepost <- ratings[ratings$ScanID %in% hrv$ScanID,]
prepost <- filter(prepost, Scan == "Pre" | Scan == "Post")
```

# Add drink group
```{r}
prepost$drinkGroup <- NA
for (i in 1:nrow(prepost)) {
  id <- prepost$ScanID[i]
  index <- grep(id, hrv$ScanID)
  prepost$drinkGroup[i] <- hrv$drinkGroup[index[1]]
}
```

# Analysis of Valence
```{r}
lmLike <- lm(Like ~ Task, prepost)
summary(lmLike)

anovaLike <- aov(Like ~ drinkGroup*Task, data = prepost)
summary(anovaLike)

tukeyLike <- TukeyHSD(anovaLike)
tukeyLike
```

# Difference between Pre Post
```{r}
prepost$diffLike <- NA
count <- 1
for (i in 1:nrow(prepost)) {
  if (count > 1 && prepost$ScanID[i] %in% diffRatings$ScanID) {
    next
  }
  scan <- prepost$ScanID[i]
  subject <- filter(prepost, ScanID == scan)
  
  task <- split(subject, subject$Task)
  for (j in 1:length(task)) {
    if (nrow(task[[j]]) != 2) {
      next
    }
    for (t in 1:nrow(task[[j]])) {
      diff <- task[[j]]$Like[2] - task[[j]]$Like[1]
      task[[j]]$diffLike[t] <- diff
    }
    
  }
  
  if (length(task) == 3) {
    subject_full <- rbind(task[[1]], task[[2]], task[[3]])
  } else {
    subject_full <- rbind(task[[1]], task[[2]])
  }
  
  
  if (count == 1) {
    diffRatings <- subject_full
  } else {
    diffRatings <- rbind(diffRatings, subject_full)
  }
  count <- count + 1
  
}
```

# Throw heart rate into the mix
```{r}
post <- filter(diffRatings, Scan == "Post")
# meanLike <- group_by(post, ScanID,Task) %>%
#              summarize(Like = mean(Like, na.rm = TRUE))
meanHR <- group_by(hrv, ScanID, Task) %>%
             summarize(HR = mean(HR, na.rm = TRUE))

post$HR <- NA
count <- 1
for (i in 1:nrow(post)) {
  if (count > 1 && post$ScanID[i] %in% LikeHR$ScanID) {
    next
  }
  scan = post$ScanID[i]
  subjectLike <- filter(post, ScanID == scan)
  subjectHR <- filter(meanHR, ScanID == scan)

  alc <- grep("Alc", subjectHR$Task)
  neut <- grep("Neut", subjectHR$Task)
  str <- grep("Str", subjectHR$Task)
    
  for (s in 1:nrow(subjectLike)) {
    if (subjectLike$Task[s] == "Alc") {
      if (!is_empty(alc)) {
        subjectLike$HR[s] <- subjectHR$HR[alc]
      }
    }
    if (subjectLike$Task[s] == "Neut") {
      if (!is_empty(neut)) {
        subjectLike$HR[s] <- subjectHR$HR[neut]
      }
    }
    if (subjectLike$Task[s] == "Str") {
      if (!is_empty(str)) {
        subjectLike$HR[s] <- subjectHR$HR[str]
      }
    }
  }
    
  if (count == 1) {
    LikeHR <- subjectLike
  } else {
    LikeHR <- rbind(LikeHR, subjectLike)
  }
  count <- count + 1
}
```


# Analyze relationship between "Like" and HR
```{r}
#LikeHR <- LikeHR[complete.cases(LikeHR[ , 13]),]
cor.test(LikeHR$HR, LikeHR$diffLike)
lmHR <- lm(HR ~ diffLike*Task, LikeHR)
summary(lmHR)

anovaHR <- aov(HR ~ diffLike*Task, data = LikeHR)
summary(anovaHR)
```

# See if Like rating is influenced by condition
```{r}
lmdiffLike <- lm(diffLike ~ Task, LikeHR)
summary(lmdiffLike)

anovadiffLike <- aov(diffLike ~ drinkGroup*Task, data = LikeHR)
summary(anovadiffLike)

tukeydiffLike <- TukeyHSD(anovadiffLike)
tukeydiffLike
```

# See if there is any significant difference only in neutral condition

```{r}
neutPost <- filter(LikeHR, Task == "Neut")

lmNeut <- lm(HR ~ diffLike, neutPost)
summary(lmNeut)
```








